### ISSUE TITLE
Tracking Zigpy issues

### ISSUE THREAD

**Issue by pipiche38** [sasu-drooz/Domoticz-Zigate#1235]
We are tracking here all of the open issues against zigpy and zigpy related radio modules, which are impacting the plugin

zigpy

- [x] https://github.com/zigpy/zigpy/discussions/1016
- [x] https://github.com/zigpy/zigpy/discussions/1011
- [x] https://github.com/zigpy/zigpy/discussions/1000
- [x] https://github.com/zigpy/zigpy/discussions/999
- [x] https://github.com/zigpy/zigpy/discussions/985
- [x] https://github.com/zigpy/zigpy/discussions/970
- [x] https://github.com/zigpy/zigpy/discussions/949
- [x] https://github.com/zigpy/zigpy-znp/issues/198
- [x] https://github.com/zigpy/zigpy/issues/1131
- [x] https://github.com/zigpy/zigpy/discussions/1375 ( https://github.com/crate-py/rpds/issues/63 )

zigpy/bellows

- [x] https://github.com/zigpy/bellows/issues/458
- [x] https://github.com/zigpy/bellows/issues/465
- [x] https://github.com/zigpy/bellows/issues/468
- [x] #1200 

zigpy/znp
- [x] https://github.com/zigpy/zigpy-znp/issues/156
- [ ] https://github.com/zigpy/zigpy-znp/issues/155
- [x] https://github.com/zigpy/zigpy-znp/issues/154
- [ ] https://github.com/zigbeefordomoticz/Domoticz-Zigbee/issues/1341
- [x] https://github.com/zigpy/zigpy-znp/issues/204

zigpy/deconz

- [ ] https://github.com/zigpy/zigpy-deconz/issues/187
- [ ] https://github.com/zigbeefordomoticz/Domoticz-Zigbee/issues/1145
- [x] https://github.com/zigpy/zigpy-deconz/issues/192

**Comment by pipiche38** [comment]
up

**Comment by Hedda** [comment]
> We are tracking here all of the open issues against zigpy and zigpy related radio modules, which are impacting the plugin
> 
> zigpy
> 
> * [ ]  [aligning ZNP and Bellows configuration zigpy/zigpy#1011](https://github.com/zigpy/zigpy/discussions/1011)
> * [ ]  [What handling recommandation when receiving  ControllerException zigpy/zigpy#1000](https://github.com/zigpy/zigpy/discussions/1000)

If you want these to be followed as issues by the upstream zigpy project then suggest (re)submitting them as new issues instead:

https://github.com/zigpy/zigpy/issues

https://github.com/zigpy/zigpy/issues/new

Issues tend to be more formal tasks, feature requests and/or bug reports which can more easily be tracked with a status.

https://docs.github.com/en/issues/tracking-your-work-with-issues/about-issues

Discussions on GitHub are just an informal communication channel which are not tracked or followed up as issues are.

https://docs.github.com/en/discussions/guides/best-practices-for-community-conversations-on-github

https://docs.github.com/en/discussions/collaborating-with-your-community-using-discussions/about-discussions

Discussions can still be cross-referenced in issues and vice versa, and people with triage permission to a repository can even create an issue from a discussion, (but then you have to get a project admin to do it so probably easier to just create new issues).

https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-an-issue#creating-an-issue-from-discussion

**Comment by pipiche38** [comment]
new issue reported with zigpy 0.63.4 

https://github.com/zigpy/zigpy/discussions/1375
https://github.com/crate-py/rpds/issues/63

**Comment by pipiche38** [comment]
> new issue reported with zigpy 0.63.4
> 
> [zigpy/zigpy#1375](https://github.com/zigpy/zigpy/discussions/1375) [crate-py/rpds#63](https://github.com/crate-py/rpds/issues/63)

workaround in place as discribed in the zigpy discussion
